### ISSUE TITLE
attach failed! (Unknown error -6)

### ISSUE THREAD

**Issue by zeefpt** [AVnu/OpenAvnu#615] opened 2017-05-31 14:13 UTC
Hi again folks,

When i try to revert to use the talker on PC 2 and listener in PC 1 gives that error :

local@pt02ipk1:/jp/OpenAvnu/examples/simple_talker$ sudo ./simple_talker -i eth3 -t 2
attaching to 0000:01:00.0
attach failed! (Unknown error -6)
connect failed (No such file or directory) - are you running as root?
local@pt02ipk1:~/jpereira/OpenAvnu/examples/simple_talker$

What should i look, im running in root.. i use sudo -i and the problem is the same! :(

And now testing the live_stream examples i got the same errors:

root@pt02ipk1:/homejp/OpenAvnu/examples/live_stream# gst-launch-1.0 ximagesrc ! videoconvert ! autovideosink | ./talker -i eth3 -t 2
attaching to 0000:01:00.0
attach failed! (Unknown error -6)
connect failed (No such file or directory) - are you running as root?

Anytip?
Regards,

**Comment by ekwang** [comment] 2017-05-31 14:19
Hi.
Let us know information of eth3.
#sudo ethtool -i eth3
or
#sudo lshw -C network

Thanks.

**Comment by zeefpt** [comment] 2017-05-31 15:00
Hi ekwang ,

Thks for response,
The problem was the driver was wrong inserted. Now i dont have the errors. But i have one doubt.
I use in PC1:
./simple_listener -i eth3 -f /home/jpereira/sample.wav 
This file have 4.5 Mb

I use in PC2:
./simple_talker -i eth0 -t 2

They communicate well and im seeing the avb packet in wireshark. 
But why the wav file is increasing side? He shouldnt  only send the .wav file from listener to talker and stops? Or are always in loop?

Regards,

**Comment by zeefpt** [comment] 2017-06-05 11:51
Im trying to do the simple audio example using:

# gst-launch-1.0 audiotestsrc ! audioconvert ! autoaudiosink | ./talker eth0 512
attaching to 000bind to iface 0000:01:00.0
checking against adapter name 0000:01:00.0
0:01:00.0
FOUND STREAM ID=6805ca5132cd0000 with state ready
FOUND STREAM ID=6805ca5133810000 with state ready
detected domain Class A PRIO=0 VID=0000...
ERC MVRP_d from mrpd
advertising stream ...
awaiting a listener ...
FOUND STREAM ID=6805ca5132cd0000 with state ready
added listener
FOUND STREAM ID=6805ca5133810000 with state ready
got a listener ...
frame sequence = 0
EVENT on STREAM ID=6805ca5132cd0000 with state ready
got a new/join indication

On listener i do:

local@pt02ipk1:~/jpereira/OpenAvnu/examples/live_stream$ sudo ./listener eth3 512 gst-launch-1.0 audiotestsrc ! audioconvert ! autoaudiosink
Msg: D:C=0,P=0,V=0000,N=0 R=6805ca5132cd QA/IN
L:D=2,S=6805ca5133810000 R=6805ca5132cd VO/IN
T:S=6805ca5132cd0000,A=91e0f0000e80,V=0000,Z=542,I=1,P=0,L=3900,B=0000000000000000,C=0 R=6805ca5132cd VO/IN

Msg: SJO T:S=6805ca5132cd0000,A=91e0f0000e80,V=0000,Z=542,I=1,P=0,L=3900 R=6805ca5132cd VO/IN

Msg: SJO L:D=2,S=6805ca5133810000 R=6805ca5132cd VO/IN

Msg: SJO D:C=0,P=0,V=0000,N=0 R=6805ca5132cd QA/IN

detected domain Class A PRIO=0 VID=0000...
Joing VLAN V++:I=0000

Waiting for talker...
Msg: ERC MVRP_d
Msg: SNE L:D=2,S=6805ca5132cd0000 R=000000000000 VN/MT

attaching to 0000:01:00.0
frame sequence = 0
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Redistribute latency...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstAudioSinkClock
Msg: SJO T:S=6805ca5132cd0000,A=91e0f0000e80,V=0000,Z=542,I=1,P=0,L=3900 R=6805ca5132cd VO/IN

Msg: SJO L:D=2,S=6805ca5133810000 R=6805ca5132cd VO/IN

Msg: SJO D:C=0,P=0,V=0000,N=0 R=6805ca5132cd VP/IN

Msg: SJO T:S=6805ca5132cd0000,A=91e0f0000e80,V=0000,Z=542,I=1,P=0,L=3900 R=6805ca5132cd VO/IN

Msg: SJO L:D=2,S=6805ca5133810000 R=6805ca5132cd VO/IN

Msg: SJO D:C=0,P=0,V=0000,N=0 R=6805ca5132cd VP/IN


But get stucked on this and dont see packets in wireshark..

Anyhelp?

**Comment by pinealservo** [comment] 2017-06-08 08:21
Original issue was caused by using the wrong driver and there are other issues open for the later question, so I'm closing the issue.

**Closed by pinealservo** 2017-06-08 08:21 UTC
Labels: question
